Skills:
  #blacksmith
  IRON_AXE: [1, 1]
  IRON_PICKAXE: [1, 1]
  IRON_SWORD: [1, 1]
  IRON_HOE: [1, 1]
  IRON_SHOVEL: [1, 1]
  BOW: [1, 1]
  SMITHING_TABLE: [1, 2]
  SHIELD: [1, 2]
  SPYGLASS: [1, 2]
  CHAIN: [1, 2]
  ANVIL: [1, 3]
  CHAINMAIL_HELMET: [1, 3]
  CHAINMAIL_CHESTPLATE: [1, 3]
  CHAINMAIL_LEGGINGS: [1, 3]
  CHAINMAIL_BOOTS: [1, 3]
  #blacksmith branch a: armorer
  IRON_HELMET: [1, 4]
  IRON_CHESTPLATE: [1, 4]
  IRON_LEGGINGS: [1, 4]
  IRON_BOOTS: [1, 4]
  GOLDEN_HELMET: [1, 4]
  GOLDEN_CHESTPLATE: [1, 4]
  GOLDEN_LEGGINGS: [1, 4]
  GOLDEN_BOOTS: [1, 4]
  DIAMOND_HELMET: [1, 5]
  DIAMOND_CHESTPLATE: [1, 5]
  DIAMOND_LEGGINGS: [1, 5]
  DIAMOND_BOOTS: [1, 5]
  NETHERITE_HELMET: [1, 6]
  NETHERITE_CHESTPLATE: [1, 6]
  NETHERITE_LEGGINGS: [1, 6]
  NETHERITE_BOOTS: [1, 6]
  #blacksmith branch b: toolsmith
  CROSSBOW: [1, 14]
  GOLDEN_AXE: [1, 14]
  GOLDEN_PICKAXE: [1, 14]
  GOLDEN_SWORD: [1, 14]
  GOLDEN_HOE: [1, 14]
  GOLDEN_SHOVEL: [1, 15]
  DIAMOND_AXE: [1, 15]
  DIAMOND_PICKAXE: [1, 15]
  DIAMOND_SWORD: [1, 15]
  DIAMOND_HOE: [1, 15]
  DIAMOND_SHOVEL: [1, 15]
  NETHERITE_AXE: [1, 16]
  NETHERITE_PICKAXE: [1, 16]
  NETHERITE_SWORD: [1, 16]
  NETHERITE_HOE: [1, 16]
  NETHERITE_SHOVEL: [1, 16]
  #farmer
  PIG: [2, 1]
  F_WHEAT: [2, 1]
  SUGAR: [2, 1]
  RABBIT: [2, 1]
  F_CARROTS: [2, 1]
  CHICKEN: [2, 2]
  BEES: [2, 2]
  WOLF: [2, 3]
  CAT: [2, 3]
  #farmer branch a: crop farmer
  F_PUMPKIN_STEM: [2, 4]
  F_COCOA: [2, 4]
  F_SUGAR_CANE: [2, 4]
  F_BROWN_MUSHROOM: [2, 4]
  F_RED_MUSHROOM: [2, 4]
  F_MELON_STEM: [2, 4]
  F_POTATOES: [2, 4]
  F_NETHER_WART: [2, 5]
  #farmer branch b: animal farmer
  SHEEP: [2, 14]
  COW: [2, 14]
  HORSE: [2, 14]
  MULE: [2, 14]
  DONKEY: [2, 14]
  LLAMA: [2, 14]
  TRADER LLAMA: [2, 14]
  TURTLE: [2, 15]
  STRIDER: [2, 15]
  MOOSHROOM: [2, 15]
  #voodooist
  BLAZE_POWDER: [3, 1] #potion of strength
  FIREBALL: [3, 1]
  BREWING_STAND: [3, 2]
  B_NETHER_WART: [3, 2]
  B_SUGAR: [3, 2] #swiftness
  B_SPIDER_EYE: [3, 2] #poison
  B_FERMENTED_SPIDER_EYE: [3, 3] #weakness/harming/slowness/invisibility
  B_GLOWSTONE_DUST: [3, 3] #increase potency
  B_REDSTONE_DUST: [3, 3] #increase duration
  E_5: [3, 3] #up to 5 bookshelf enchantments
  ENCHANTMENT_TABLE: [3, 3]
  GOLDEN_APPLE: [3, 3]
  GOLDEN_CARROT: [3, 3] #night vision
  NETHER_PORTAL: [3, 3] #make portal
  #brewer
  B_GUNPOWDER: [3, 4] #splash potion
  B_RABBITS_FOOT: [3, 4] #leaping
  B_GHAST_TEAR: [3, 4] #regeneration
  B_PHANTOM_MEMBRANE: [3, 4] #slow falling
  B_GOLDEN_CARROT: [3 4] #night vision
  B_MAGMA_CREAM: [3, 5] #fire resistance
  B_PUFFERFISH: [3, 5] #water breathing
  GLISTERING_MELON_SLICE: [3, 4]
  B_GLISTERING_MELON_SLICE: [3, 5] #healing
  #enchanting
  E_BOOK: [3, 14] #use enchantment books in anvils
  E_10: [3, 14] #up to 10 bookshelf enchantmnets
  E_15: [3, 15] #up to 15 bookshelf enchan,=tments (lvl 30)
  TOTEM_OF_UNDYING: [3, 16]
  #stoneworker
  WHITE_CONCRETE_POWDER: [4, 1]
  ORANGE_CONCRETE_POWDER: [4, 1]
  MAGENTA_CONCRETE_POWDER: [4, 1]
  LIGHT_BLUE_CONCRETE_POWDER: [4, 1]
  YELLOW_CONCRETE_POWDER: [4, 1]
  LIME_CONCRETE_POWDER: [4, 1]
  PINK_CONCRETE_POWDER: [4, 1]
  GRAY_CONCRETE_POWDER: [4, 1]
  LIGHT_GRAY_CONCRETE_POWDER: [4, 1]
  CYAN_CONCRETE_POWDER: [4, 1]
  BLUE_CONCRETE_POWDER: [4, 1]
  BROWN_CONCRETE_POWDER: [4, 1]
  GREEN_CONCRETE_POWDER: [4, 1]
  RED_CONCRETE_POWDER: [4, 1]
  BLACK_CONCRETE_POWDER: [4, 1]
  COOK_CLAY: [4, 1]
  SANDSTONE: [4, 1]
  SMOOTH_STONE: [4, 1]
  SMOOTH_STONE_SLAB: [4, 1]
  MUD_BRICKS: [4, 1]
  MUD_BRICK_WALL: [4, 1]
  RED_SANDSTONE_SLAB: [4, 1]
  SMOOTH_RED_SANDSTONE_SLAB: [4, 1]
  DIORITE_SLAB: [4, 1]
  DIORITE_STAIRS: [4, 1]
  GRANITE_SLAB: [4, 1]
  GRANITE_STAIRS: [4, 1]
  ANDESITE_SLAB: [4, 1]
  ANDESITE_STAIRS: [4, 1]
  COBBLED_DEEPSLATE_SLAB: [4, 1]
  COBBLED_DEEPSLATE_STAIRS: [4, 1]
  COBBLED_DEEPSLATE_WALL: [4, 1]
  COBBLESTONE_WALL: [4, 1]
  COBBLESTONE_STAIRS: [4, 1]
  COBBLESTONE_SLAB: [4, 1]
  CHISELED_SANDSTONE: [4, 1]
  CUT_SANDSTONE: [4, 1]
  SMOOTH_SANDSTONE: [4, 1]
  SMOOTH_SANDSTONE_SLAB: [4, 1]
  SMOOTH_SANDSTONE_STAIRS: [4, 1]
  SANDSTONE_STAIRS: [4, 1]
  SANDSTONE_SLAB: [4, 1]
  CUT_SANDSTONE_SLAB: [4, 1]
  STONE_BRICKS: [ 4, 2 ]
  STONE_BRICK_WALL: [ 4, 2 ]
  SMOOTH_STONE_BRICKS: [ 4, 2 ]
  STONE_BRICK_SLAB: [4,2]
  CHISELED_STONE_BRICKS: [ 4, 2 ]
  MOSSY_STONE_BRICKS: [ 4, 2 ]
  STONECUTTER: [4, 2]
  GRINDSTONE: [4, 2]
  MOSSY_COBBLESTONE_WALL: [4, 2]
  BRICKS: [4, 2]
  BRICK_SLAB: [4, 2]
  BRICK: [4, 2]
  BRICK_WALL: [4, 2]
  DEEPSLATE_WALL: [4, 2]
  DEEPSLATE_TILE_SLAB: [4, 2]
  DEEPSLATE_BRICKS: [4, 2]
  DEEPSLATE_BRICK_SLAB: [4, 2]
  DEEPSLATE_BRICK_STAIRS: [4, 2]
  POLISHED_DEEPSLATE_SLAB: [4, 2]
  POLISHED_DEEPSLATE: [4, 4]
  POLISHED_DEEPSLATE_WALL: [4, 4]
  POLISHED_DEEPSLATE_BRICKS: [4, 4]
  POLISHED_DEEPSLATE_BRICK_WALL: [4, 4]
  DEEPSLATE_TILES: [4, 4]
  DEEPSLATE_TILE_WALL: [4, 4]
  IRON_BARS: [4, 3]
  POLISHED_ANDESITE: [4, 3]
  POLISHED_GRANITE: [4, 3]
  POLISHED_DIORITE: [4, 3]
  POLISHED_DIORITE_SLAB: [4, 3]
  POLISHED_DIORITE_STAIRS: [4, 3]
  POLISHED_GRANITE_SLAB: [4, 3]
  POLISHED_GRANITE_STAIRS: [4, 3]
  POLISHED_ANDESITE_SLAB: [4, 3]
  POLISHED_ANDESITE_STAIRS: [4, 3]
  ANDESITE_WALL: [4, 3]
  DIORITE_WALL: [4, 3]
  GRANITE_WALL: [4, 3]
  SANDSTONE_WALL: [4, 3]
  BLACKSTONE_SLAB: [4, 3]
  BLACKSTONE_WALL: [4, 3]
  BLOCK_OF_QUARTZ: [4, 3]
  POLISHED_BLACKSTONE: [4, 4]
  POLISHED_BLACKSTONE_BRICKS: [4, 4]
  POLISHED_BLACKSTONE_WALL: [4, 4]
  POLISHED_BLACKSTONE_BRICK_WALL: [4, 4]
  PRISMARINE_SLAB: [4, 4]
  PRISMARINE_BRICK_SLAB: [4, 4]
  DARK_PRISMARINE_SLAB: [4, 4 ]
  PRISMARINE: [4, 4]
  DARK_PRISMARINE: [4, 4]
  PRISMARINE_STAIRS: [4, 4]
  PRISMARINE_BRICK_STAIRS: [4, 4]
  DARK_PRISMARINE_STAIRS: [4, 4]
  PRISMARINE_WALL: [4, 4]
  PRISMARINE_BRICKS: [4, 4]
  CHISELED_QUARTZ_BLOCK: [4, 4]
  QUARTZ_PILLAR: [4, 4]
  QUARTZ_BRICKS: [4, 4]
  NETHER_BRICKS: [4, 5]
  NETHER_BRICK_WALL: [4, 5]
  NETHER_BRICK_SLAB: [4, 5]
  NETHER_BRICK_FENCE: [4, 5]
  NETHER_BRICK_STAIRS: [4, 5]
  CHISELED_NETHER_BRICKS: [4, 5]
  RED_NETHER_BRICKS: [4, 5]
  RED_NETHER_BRICK_WALL: [4, 5]
  RED_NETHER_BRICK_SLAB: [4, 5]
  RED_NETHER_BRICK_STAIRS: [4, 5]
  END_STONE_BRICKS: [4, 5]
  END_STONE_BRICK_WALL: [4, 5]
  END_STONE_BRICK_STAIRS: [4, 5]
  END_STONE_BRICK_SLAB: [4, 5]
  PURPUR_SLAB: [4, 5]
  PURPUR_BLOCK: [4, 5]
  PURPUR_PILLAR: [4, 5]
  PURPUR_STAIRS: [4, 5]
  #artisan
  LEATHER_HELMET: [5, 1]
  LEATHER_CHESTPLATE: [5, 1]
  LEATHER_LEGGINGS: [5, 1]
  LEATHER_BOOTS: [5, 1]
  GLASS_BOTTLE: [5, 1]
  BARREL: [5, 1]
  PAPER: [5, 1]
  BOOK: [5, 2]
  BOOK_AND_QUILL: [5, 2]
  FLOWER_POT: [5, 2]
  CANDLE: [5, 2]
  CARPET: [5, 2]
  GLASS_PANE: [5, 2]
  ITEM_FRAME: [5, 2]
  MAP: [5, 2]
  CARTOGRAPHY_TABLE: [5, 2]
  LANTERN: [5, 2]
  COMPASS: [5, 2]
  CLOCK: [5, 3]
  BUNDLE: [5, 3]
  GLOW_ITEM_FRAME: [5, 3]
  SCAFFOLDING: [5, 3]
  PAINTING: [5, 3]
  SOUL_LANTERN: [5, 3]
  REDSTONE_LAMP: [5, 3]
  BOOKSHELF: [5, 3]
  DAYLIGHT_DETECTOR: [5, 3]
  ARMOR_STAND: [5, 3]
  GLOWSTONE_BLOCK: [5, 3]
  NOTE_BLOCK: [5, 3]
  LOOM: [5, 4]
  WHITE_BANNER: [5, 4]
  LIGHT_BLUE_BANNER: [5, 4]
  YELLOW_BANNER: [5, 4]
  LIME_BANNER: [5, 4]
  PINK_BANNER: [5, 4]
  GRAY_BANNER: [5, 4]
  LIGHT_GRAY_BANNER: [5, 4]
  CYAN_BANNER: [5, 4]
  PURPLE_BANNER: [5, 4]
  BLUE_BANNER: [5, 4]
  BROWN_BANNER: [5, 4]
  GREEN_BANNER: [5, 4]
  RED_BANNER: [5, 4]
  BLACK_BANNER: [5, 4]
  NAME_TAG: [5, 5]
  JUKEBOX: [5, 5]
  END_ROD: [5, 5]
  SADDLE: [5, 5]
  #Chef
  Dough: [6, 1]
  Bread: [6, 1, 0]
  Sweet_Dough: [6, 2]
  Sweet_Bread: [6, 2, 4]
  Sweet_Berry_Wine: [6, 2, 2]
  Beer: [6, 2, 1]
  RABBIT_STEW: [6, 2]
  COFFEE: [6, 3]
  COOKIE: [6, 3]
  MUSHROOM_STEW: [6, 3]
  BEETROOT_SOUP: [6, 3]
  Vodka: [6, 3, 1]
  CAKE: [6, 4]
  PUMPKIN_PIE: [6, 5]

  COOK_Dough: [6, 2]
  COOK_Sweet_Dough: [6, 2]

CustomCookNames:
  Sweet_Dough: "Sweet Bread"

Cookable:
  - "WHITE_DYE"
  - "RED_DYE"

Uncraftable:
  - "BREAD"

Crops:
  SUGAR_CANE: [85, 110]
  AIR: [85, 110]
  PUMPKIN: [65, 85]
  PUMPKIN_STEM: [65, 85]
  MELON: [80, 100]
  MELON_STEM: [80, 100]
  WHEAT: [65, 80]
  POTATOES: [55, 80]
  CARROTS: [55, 75]
  CACTUS: [90, 200]
  BEETROOTS: [50, 70]
  BAMBOO: [-10, 100]
  COCOA: [80, 110]
  SWEET_BERRY_BUSH: [20, 50]
  NETHER_WART: [75, 200]
  OAK_SAPLING: [65, 75]
  SPRUCE_SAPLING: [30, 40]
  DARK_OAK_SAPLING: [45, 60]
  BIRCH_SAPLING: [55, 70]
  ACACIA_SAPLING: [70, 122]
  JUNGLE_SAPLING: [80, 120]
  AZALEA: [0, 95]
  FLOWERING_AZALEA: [0, 95]
  BROWN_MUSHROOM: [80, 120]
  RED_MUSHROOM: [80, 120]

Animals:
  COW: [25, 65]
  CHICKEN: [0, 80]
  SHEEP: [50, 75]
  PIG: [45, 75]
  RABBIT: [50, 80]
  BEES: [30, 100]

Professions:
  1: "Blacksmith"
  2: "Farmer"
  3: "Voodooist"
  4: "Stoneworker"
  5: "Artisan"
  6: "Chef"

GlobalWarmingFactor: 0.0
